{
    "status": "OK",
    "copyright": "Copyright (c) 2017 Pro Publica Inc. All Rights Reserved.",
    "results": [{
        "id": "B001260",
        "member_uri": "https://api.propublica.org/congress/v1/members/B001260.json",
        "name": "Vern Buchanan",
        "num_results": 20,
        "offset": 0,
        "bills": [{
                "congress": "115",
                "bill_id": "hr1-115",
                "bill_type": "hr",
                "number": "H.R.1",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr1.json",
                "title": "To provide for reconciliation pursuant to title II of the concurrent resolution on the budget for fiscal year 2018.",
                "short_title": "Tax Cuts and Jobs Act",
                "cosponsored_date": "2017-11-02",

                "sponsor_title": "Rep.",
                "sponsor_id": "B000755",
                "sponsor_name": "Kevin Brady",
                "sponsor_state": "TX",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/B000755.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/1",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr1",
                "introduced_date": "2017-11-02",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 24,
                "cosponsors_by_party": {
                    "R": 24
                },
                "committees": "House Ways and Means Committee",
                "primary_subject": "Taxation",
                "summary": "Tax Cuts and Jobs Act  This bill amends the Internal Revenue Code to reduce tax rates and modify policies, credits, and deductions for individuals and businesses.  With respect to individuals, the bill:    replaces the seven existing tax brackets (10%, 15%, 25%, 28%, 33%, 35%, and 39.6%) with four brackets (12%, 25%, 35%, and 39.6%), increases the standard deduction,   repeals the deduction for personal exemptions,  establishes a 25% maximum rate on the business income of individuals,   increases the child tax credit and establishes a new family tax credit,  repeals the overall limitation on certain itemized deductions,   limits the mortgage interest deduction for debt incurred after November 2, 2017, to mortgages of up to $500,000 (currently $1 million), repeals the deduction for state and local income or sales taxes not paid or accrued in a trade or business,   repeals the deduction for medical expenses,   consolidates and repeals several education-related deductions and credits,   repeals the alternative minimum tax, and  repeals the estate and generation-skipping transfer taxes in six years.   For businesses, the bill:   reduces the corporate tax rate from a maximum of 35% to a flat 20% rate (25% for personal services corporations),   allows increased expensing of the costs of certain property,   limits the deductibility of net interest expenses to 30% percent of the business's adjusted taxable income,  repeals the work opportunity tax credit,   terminates the exclusion for interest on private activity bonds,   modifies or repeals various energy-related deductions and credits,   modifies the taxation of foreign income, and  imposes an excise tax on certain payments from domestic corporations to related foreign corporations.   The bill also repeals or modifies several additional credits and deductions for individuals and businesses. ",
                "summary_short": "Tax Cuts and Jobs Act  This bill amends the Internal Revenue Code to reduce tax rates and modify policies, credits, and deductions for individuals and businesses.  With respect to individuals, the bill:    replaces the seven existing tax brackets (10%, 15%, 25%, 28%, 33%, 35%, and 39.6%) with four brackets (12%, 25%, 35%, and 39.6%), increases the standard deduction,   repeals the deduction for personal exemptions,  establishes a 25% maximum rate on the business income of individuals,   incre...",
                "latest_major_action_date": "2017-11-02",
                "latest_major_action": "Referred to the House Committee on Ways and Means."
            },
            {
                "congress": "115",
                "bill_id": "hr4202-115",
                "bill_type": "hr",
                "number": "H.R.4202",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr4202.json",
                "title": "To amend the Animal Welfare Act to prohibit animal fighting in United States territories.",
                "short_title": "PACE Act",
                "cosponsored_date": "2017-11-01",

                "sponsor_title": "Rep.",
                "sponsor_id": "R000580",
                "sponsor_name": "Peter Roskam",
                "sponsor_state": "IL",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/R000580.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/4202",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr4202",
                "introduced_date": "2017-11-01",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 8,
                "cosponsors_by_party": {
                    "D": 4,
                    "R": 4
                },
                "committees": "House Agriculture Committee",
                "primary_subject": "",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-11-01",
                "latest_major_action": "Referred to the House Committee on Agriculture."
            },
            {
                "congress": "115",
                "bill_id": "hr820-115",
                "bill_type": "hr",
                "number": "H.R.820",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr820.json",
                "title": "To maximize discovery, and accelerate development and availability, of promising childhood cancer treatments, and for other purposes.",
                "short_title": "Childhood Cancer STAR Act",
                "cosponsored_date": "2017-10-31",

                "sponsor_title": "Rep.",
                "sponsor_id": "M001157",
                "sponsor_name": "Michael McCaul",
                "sponsor_state": "TX",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/M001157.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/820",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr820",
                "introduced_date": "2017-02-02",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 304,
                "cosponsors_by_party": {
                    "D": 168,
                    "R": 136
                },
                "committees": "House Energy and Commerce Committee",
                "primary_subject": "Health",
                "summary": "Childhood Cancer Survivorship, Treatment, Access, and Research Act of 2017 or the Childhood Cancer STAR Act  This bill amends the Public Health Service Act to authorize the National Institutes of Health (NIH) to provide support to collect the medical specimens and information of children, adolescents, and young adults with selected cancers that have the least effective treatments in order to achieve a better understanding of these cancers and the effects of treatment. The national childhood cancer registry is reauthorized through FY2022 and revised to authorize the Centers for Disease Control and Prevention to award grants to state cancer registries to improve tracking of childhood cancers. The Department of Health and Human Services (HHS) may: (1) support pilot programs to develop or study models for monitoring and caring for childhood cancer survivors throughout their lives, (2) establish a task force to develop and test standards for high-quality childhood cancer survivorship care, and (3) carry out a demonstration project to improve care coordination as childhood cancer survivors transition to adult care. HHS must convene a Workforce Development Collaborative on Medical and Psychosocial Care for Pediatric Cancer Survivors. The NIH may support research on: (1) outcomes for, and barriers faced by, pediatric cancer survivors within minority or medically underserved populations; and (2) follow-up care for pediatric cancer survivors, including research on the late effects of cancer treatment and long-term complications. The Government Accountability Office must make recommendations to address barriers to childhood cancer survivors obtaining and paying for adequate medical care.",
                "summary_short": "Childhood Cancer Survivorship, Treatment, Access, and Research Act of 2017 or the Childhood Cancer STAR Act  This bill amends the Public Health Service Act to authorize the National Institutes of Health (NIH) to provide support to collect the medical specimens and information of children, adolescents, and young adults with selected cancers that have the least effective treatments in order to achieve a better understanding of these cancers and the effects of treatment. The national childhood c...",
                "latest_major_action_date": "2017-02-03",
                "latest_major_action": "Referred to the Subcommittee on Health."
            },
            {
                "congress": "115",
                "bill_id": "hr747-115",
                "bill_type": "hr",
                "number": "H.R.747",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr747.json",
                "title": "To amend the Internal Revenue Code of 1986 to reform taxation of alcoholic beverages.",
                "short_title": "Craft Beverage Modernization and Tax Reform Act of 2017",
                "cosponsored_date": "2017-10-25",

                "sponsor_title": "Rep.",
                "sponsor_id": "P000594",
                "sponsor_name": "Erik Paulsen",
                "sponsor_state": "MN",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/P000594.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/747",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr747",
                "introduced_date": "2017-01-30",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 293,
                "cosponsors_by_party": {
                    "D": 127,
                    "R": 166
                },
                "committees": "House Ways and Means Committee",
                "primary_subject": "Taxation",
                "summary": "Craft Beverage Modernization and Tax Reform Act of 2017  This bill amends the Internal Revenue Code, with respect to the tax treatment of certain alcoholic beverages, to:    exclude the aging period from the production period for beer, wine, or distilled spirits for purposes of determining whether a taxpayer can expense, rather than capitalize, interest costs paid or incurred during the production period;   reduce excise tax rates on beer and distilled spirits;   modify the small wine producer tax credit to increase the amount of the credit, expand the producers that are covered, and specify an adjustment for hard cider; modify the alcohol content limitations that apply to certain wines for tax purposes;  specify definitions for \"mead\" and \"low alcohol by volume wine;\"  modify requirements for records, statements, and returns for certain breweries; and   permit the transfer of beer between bonded facilities without payment of tax.   The Department of the Treasury must amend applicable regulations with respect to the use of wholesome products suitable for human consumption in the production of fermented beverages. ",
                "summary_short": "Craft Beverage Modernization and Tax Reform Act of 2017  This bill amends the Internal Revenue Code, with respect to the tax treatment of certain alcoholic beverages, to:    exclude the aging period from the production period for beer, wine, or distilled spirits for purposes of determining whether a taxpayer can expense, rather than capitalize, interest costs paid or incurred during the production period;   reduce excise tax rates on beer and distilled spirits;   modify the small wine produce...",
                "latest_major_action_date": "2017-01-30",
                "latest_major_action": "Referred to the House Committee on Ways and Means."
            },
            {
                "congress": "115",
                "bill_id": "hr4042-115",
                "bill_type": "hr",
                "number": "H.R.4042",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr4042.json",
                "title": "To designate the facility of the United States Postal Service located at 1415 West Oak Street, in Kissimmee, Florida, as the 'Borinqueneers Post Office Building'.",
                "short_title": "To designate the facility of the United States Postal Service located at 1415 West Oak Street, in Kissimmee, Florida, as the \"Borinqueneers Post Office Building\".",
                "cosponsored_date": "2017-10-12",

                "sponsor_title": "Rep.",
                "sponsor_id": "S001200",
                "sponsor_name": "Darren Soto",
                "sponsor_state": "FL",
                "sponsor_party": "D",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/S001200.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/4042",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr4042",
                "introduced_date": "2017-10-12",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 26,
                "cosponsors_by_party": {
                    "R": 16,
                    "D": 10
                },
                "committees": "House Oversight and Government Reform Committee",
                "primary_subject": "Government Operations and Politics",
                "summary": "Designates the facility of the United States Postal Service located at 1415 West Oak Street, in Kissimmee, Florida, as the \"Borinqueneers Post Office Building.\"",
                "summary_short": "Designates the facility of the United States Postal Service located at 1415 West Oak Street, in Kissimmee, Florida, as the &quot;Borinqueneers Post Office Building.&quot;",
                "latest_major_action_date": "2017-10-12",
                "latest_major_action": "Referred to the House Committee on Oversight and Government Reform."
            },
            {
                "congress": "115",
                "bill_id": "hr3329-115",
                "bill_type": "hr",
                "number": "H.R.3329",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr3329.json",
                "title": "To amend the Hizballah International Financing Prevention Act of 2015 to impose additional sanctions with respect to Hizballah, and for other purposes.",
                "short_title": "Hizballah International Financing Prevention Amendments Act of 2017",
                "cosponsored_date": "2017-10-04",

                "sponsor_title": "Rep.",
                "sponsor_id": "R000487",
                "sponsor_name": "Edward Royce",
                "sponsor_state": "CA",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/R000487.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/3329",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr3329",
                "introduced_date": "2017-07-20",
                "active": true,
                "last_vote": null,
                "house_passage": "2017-10-25",
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 114,
                "cosponsors_by_party": {
                    "D": 47,
                    "R": 67
                },
                "committees": "House Judiciary Committee",
                "primary_subject": "International Affairs",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-10-26",
                "latest_major_action": "Received in the Senate. Read twice. Placed on Senate Legislative Calendar under General Orders. Calendar No. 253."
            },
            {
                "congress": "115",
                "bill_id": "hr3826-115",
                "bill_type": "hr",
                "number": "H.R.3826",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr3826.json",
                "title": "To amend title XXVIII of the Public Health Service Act to establish a National Advisory Committee on Seniors and Disasters.",
                "short_title": "Protecting Seniors During Disasters Act",
                "cosponsored_date": "2017-10-04",

                "sponsor_title": "Rep.",
                "sponsor_id": "F000462",
                "sponsor_name": "Lois Frankel",
                "sponsor_state": "FL",
                "sponsor_party": "D",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/F000462.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/3826",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr3826",
                "introduced_date": "2017-09-25",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 11,
                "cosponsors_by_party": {
                    "R": 4,
                    "D": 7
                },
                "committees": "House Energy and Commerce Committee",
                "primary_subject": "Health",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-09-29",
                "latest_major_action": "Referred to the Subcommittee on Health."
            },
            {
                "congress": "115",
                "bill_id": "hr2790-115",
                "bill_type": "hr",
                "number": "H.R.2790",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr2790.json",
                "title": "To phase out cosmetic animal testing and the sale of cosmetics tested on animals, and for other purposes.",
                "short_title": "Humane Cosmetics Act",
                "cosponsored_date": "2017-10-03",

                "sponsor_title": "Rep.",
                "sponsor_id": "M001197",
                "sponsor_name": "Martha McSally",
                "sponsor_state": "AZ",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/M001197.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/2790",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr2790",
                "introduced_date": "2017-06-06",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 145,
                "cosponsors_by_party": {
                    "D": 128,
                    "R": 17
                },
                "committees": "House Energy and Commerce Committee",
                "primary_subject": "Animals",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-06-09",
                "latest_major_action": "Referred to the Subcommittee on Health."
            },
            {
                "congress": "115",
                "bill_id": "hr1697-115",
                "bill_type": "hr",
                "number": "H.R.1697",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr1697.json",
                "title": "To amend the Export Administration Act of 1979 to include in the prohibitions on boycotts against allies of the United States boycotts fostered by international governmental organizations against Israel and to direct the Export-Import Bank of the United States to oppose boycotts against Israel, and for other purposes.",
                "short_title": "Israel Anti-Boycott Act",
                "cosponsored_date": "2017-09-28",

                "sponsor_title": "Rep.",
                "sponsor_id": "R000580",
                "sponsor_name": "Peter Roskam",
                "sponsor_state": "IL",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/R000580.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/1697",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr1697",
                "introduced_date": "2017-03-23",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 269,
                "cosponsors_by_party": {
                    "D": 69,
                    "R": 200
                },
                "committees": "House Financial Services Committee",
                "primary_subject": "Foreign Trade and International Finance",
                "summary": "Israel Anti-Boycott Act This bill declares that Congress: (1) opposes the United Nations Human Rights Council resolution of March 24, 2016, which urges countries to pressure companies to divest from, or break contracts with, Israel; and (2) encourages full implementation of the United States-Israel Strategic Partnership Act of 2014 through enhanced, governmentwide, coordinated U.S.-Israel scientific and technological cooperation in civilian areas.  The bill amends the Export Administration Act of 1979 to declare that it shall be U.S. policy to oppose:   requests by foreign countries to impose restrictive practices or boycotts against other countries friendly to the United States or against U.S. persons; and  restrictive trade practices or boycotts fostered or imposed by an international governmental organization, or requests to impose such practices or boycotts, against Israel.   The bill prohibits any U.S. person engaged interstate or foreign commerce from supporting:    any request by a foreign country to impose any boycott against a country that is friendly to the United States and that is not itself the object of any form of boycott pursuant to United States law or regulation, or   any boycott fostered or imposed by any international governmental organization against Israel or any request by any international governmental organization to impose such a boycott.  The bill amends the Export-Import Bank Act of 1945 to include as a reason for the Export-Import Bank to deny credit applications for the export of goods and services between the United States and foreign countries, opposition to policies and actions that are politically motivated and are intended to penalize or otherwise limit commercial relations specifically with citizens or residents of Israel, entities organized under the laws of Israel, or the government of Israel.",
                "summary_short": "Israel Anti-Boycott Act This bill declares that Congress: (1) opposes the United Nations Human Rights Council resolution of March 24, 2016, which urges countries to pressure companies to divest from, or break contracts with, Israel; and (2) encourages full implementation of the United States-Israel Strategic Partnership Act of 2014 through enhanced, governmentwide, coordinated U.S.-Israel scientific and technological cooperation in civilian areas.  The bill amends the Export Administration Ac...",
                "latest_major_action_date": "2017-03-23",
                "latest_major_action": "Referred to House Financial Services"
            },
            {
                "congress": "115",
                "bill_id": "hr3893-115",
                "bill_type": "hr",
                "number": "H.R.3893",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr3893.json",
                "title": "To designate the facility of the United States Postal Service located at 100 Mathe Avenue in Interlachen, Florida, as the 'Robert H. Jenkins Post Office'.",
                "short_title": "To designate the facility of the United States Postal Service located at 100 Mathe Avenue in Interlachen, Florida, as the \"Robert H. Jenkins Post Office\".",
                "cosponsored_date": "2017-09-28",

                "sponsor_title": "Rep.",
                "sponsor_id": "Y000065",
                "sponsor_name": "Ted Yoho",
                "sponsor_state": "FL",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/Y000065.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/3893",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr3893",
                "introduced_date": "2017-09-28",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 26,
                "cosponsors_by_party": {
                    "R": 15,
                    "D": 11
                },
                "committees": "House Oversight and Government Reform Committee",
                "primary_subject": "Government Operations and Politics",
                "summary": "Designates the facility of the United States Postal Service located at 100 Mathe Avenue in Interlachen, Florida, as the \"Robert H. Jenkins Post Office.\"",
                "summary_short": "Designates the facility of the United States Postal Service located at 100 Mathe Avenue in Interlachen, Florida, as the &quot;Robert H. Jenkins Post Office.&quot;",
                "latest_major_action_date": "2017-11-02",
                "latest_major_action": "Ordered to be Reported by Unanimous Consent."
            },
            {
                "congress": "115",
                "bill_id": "hr3312-115",
                "bill_type": "hr",
                "number": "H.R.3312",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr3312.json",
                "title": "To amend the Dodd-Frank Wall Street Reform and Consumer Protection Act to specify when bank holding companies may be subject to certain enhanced supervision, and for other purposes.",
                "short_title": "Systemic Risk Designation Improvement Act of 2017",
                "cosponsored_date": "2017-09-25",

                "sponsor_title": "Rep.",
                "sponsor_id": "L000569",
                "sponsor_name": "Blaine Luetkemeyer",
                "sponsor_state": "MO",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000569.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/3312",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr3312",
                "introduced_date": "2017-07-19",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 69,
                "cosponsors_by_party": {
                    "D": 15,
                    "R": 48
                },
                "committees": "House Financial Services Committee",
                "primary_subject": "Finance and Financial Sector",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-10-12",
                "latest_major_action": "Ordered to be Reported (Amended) by the Yeas and Nays: 47 - 12."
            },
            {
                "congress": "115",
                "bill_id": "hr3638-115",
                "bill_type": "hr",
                "number": "H.R.3638",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr3638.json",
                "title": "To designate the facility of the United States Postal Service located at 1100 Kings Road in Jacksonville, Florida, as the 'Rutledge Pearson Post Office Building'.",
                "short_title": "To designate the facility of the United States Postal Service located at 1100 Kings Road in Jacksonville, Florida, as the \"Rutledge Pearson Post Office Building\".",
                "cosponsored_date": "2017-09-05",

                "sponsor_title": "Rep.",
                "sponsor_id": "L000586",
                "sponsor_name": "Al Lawson",
                "sponsor_state": "FL",
                "sponsor_party": "D",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000586.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/3638",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr3638",
                "introduced_date": "2017-08-01",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 26,
                "cosponsors_by_party": {
                    "R": 16,
                    "D": 10
                },
                "committees": "House Oversight and Government Reform Committee",
                "primary_subject": "Government Operations and Politics",
                "summary": "Designates the facility of the United States Postal Service located at 1100 Kings Road in Jacksonville, Florida, as the \"Rutledge Pearson Post Office Building.\"",
                "summary_short": "Designates the facility of the United States Postal Service located at 1100 Kings Road in Jacksonville, Florida, as the &quot;Rutledge Pearson Post Office Building.&quot;",
                "latest_major_action_date": "2017-08-01",
                "latest_major_action": "Referred to the House Committee on Oversight and Government Reform."
            },
            {
                "congress": "115",
                "bill_id": "hr2133-115",
                "bill_type": "hr",
                "number": "H.R.2133",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr2133.json",
                "title": "To provide regulatory relief to community financial institutions, and for other purposes.",
                "short_title": "CLEARR Act of 2017",
                "cosponsored_date": "2017-08-29",

                "sponsor_title": "Rep.",
                "sponsor_id": "L000569",
                "sponsor_name": "Blaine Luetkemeyer",
                "sponsor_state": "MO",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/L000569.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/2133",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr2133",
                "introduced_date": "2017-04-25",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 53,
                "cosponsors_by_party": {
                    "R": 53
                },
                "committees": "House Financial Services Committee",
                "primary_subject": "Finance and Financial Sector",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-07-12",
                "latest_major_action": "Hearings Held by the Subcommittee on Financial Institutions and Consumer Credit Prior to Referral."
            },
            {
                "congress": "115",
                "bill_id": "hr2327-115",
                "bill_type": "hr",
                "number": "H.R.2327",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr2327.json",
                "title": "To direct the Secretary of Veterans Affairs to make grants to eligible organizations to provide service dogs to veterans with severe post-traumatic stress disorder, and for other purposes.",
                "short_title": "PAWS Act of 2017",
                "cosponsored_date": "2017-07-28",

                "sponsor_title": "Rep.",
                "sponsor_id": "D000621",
                "sponsor_name": "Ron DeSantis",
                "sponsor_state": "FL",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/D000621.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/2327",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr2327",
                "introduced_date": "2017-05-03",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 205,
                "cosponsors_by_party": {
                    "D": 92,
                    "R": 110
                },
                "committees": "House Veterans&#39; Affairs Committee",
                "primary_subject": "Armed Forces and National Security",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-09-26",
                "latest_major_action": "Subcommittee Hearings Held."
            },
            {
                "congress": "115",
                "bill_id": "hr3332-115",
                "bill_type": "hr",
                "number": "H.R.3332",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr3332.json",
                "title": "To award the Congressional Gold Medal to Bob Dole, in recognition for his service to the nation as a soldier, legislator, and statesman.",
                "short_title": "Bob Dole Congressional Gold Medal Act",
                "cosponsored_date": "2017-07-26",

                "sponsor_title": "Rep.",
                "sponsor_id": "J000290",
                "sponsor_name": "Lynn Jenkins",
                "sponsor_state": "KS",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/J000290.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/3332",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr3332",
                "introduced_date": "2017-07-20",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 89,
                "cosponsors_by_party": {
                    "R": 54,
                    "D": 35
                },
                "committees": "House Financial Services Committee",
                "primary_subject": "Congress",
                "summary": "Bob Dole Congressional Gold Medal Act  This bill directs the Speaker of the House of Representatives and the President pro tempore of the Senate to arrange for the award of a Congressional Gold Medal to Bob Dole in recognition for his service to the nation as a soldier, legislator, and statesman.",
                "summary_short": "Bob Dole Congressional Gold Medal Act  This bill directs the Speaker of the House of Representatives and the President pro tempore of the Senate to arrange for the award of a Congressional Gold Medal to Bob Dole in recognition for his service to the nation as a soldier, legislator, and statesman.",
                "latest_major_action_date": "2017-07-20",
                "latest_major_action": "Referred to the House Committee on Financial Services."
            },
            {
                "congress": "115",
                "bill_id": "hr398-115",
                "bill_type": "hr",
                "number": "H.R.398",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr398.json",
                "title": "To amend title 18, United States Code, with respect to civil forfeitures relating to certain seized animals.",
                "short_title": "HEART Act of 2017",
                "cosponsored_date": "2017-07-20",

                "sponsor_title": "Rep.",
                "sponsor_id": "K000386",
                "sponsor_name": "John Katko",
                "sponsor_state": "NY",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/K000386.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/398",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr398",
                "introduced_date": "2017-01-10",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 63,
                "cosponsors_by_party": {
                    "D": 33,
                    "R": 30
                },
                "committees": "House Judiciary Committee",
                "primary_subject": "Crime and Law Enforcement",
                "summary": "Help Extract Animals from Red Tape Act of 2017 or the HEART Act of 2017  This bill amends the federal criminal code to modify the notice period in civil forfeiture proceedings that involve the seizure of an animal involved in animal fighting. It requires the government to send notice of the seizure to interested parties within 30 days (currently, 60 days). The notice period may be extended only if a delay is warranted after considering certain factors, including the cost to the government of providing shelter for the animal, the health of the animal and the effect of a delay on its rehabilitation, and any increased risk that a delay could necessitate the euthanasia of the animal. The bill amends the federal judicial code to authorize the Department of Justice to use amounts from the Department of Justice Assets Forfeiture Fund to pay for costs associated with a seized animal, including transportation, shelter, care, veterinary services, and humane euthanasia.",
                "summary_short": "Help Extract Animals from Red Tape Act of 2017 or the HEART Act of 2017  This bill amends the federal criminal code to modify the notice period in civil forfeiture proceedings that involve the seizure of an animal involved in animal fighting. It requires the government to send notice of the seizure to interested parties within 30 days (currently, 60 days). The notice period may be extended only if a delay is warranted after considering certain factors, including the cost to the government of ...",
                "latest_major_action_date": "2017-02-06",
                "latest_major_action": "Referred to the Subcommittee on Crime, Terrorism, Homeland Security, and Investigations."
            },
            {
                "congress": "115",
                "bill_id": "hr3305-115",
                "bill_type": "hr",
                "number": "H.R.3305",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr3305.json",
                "title": "To amend titles 23 and 49, United States Code, with respect to bikeshare projects, and for other purposes.",
                "short_title": "Bikeshare Transit Act of 2017",
                "cosponsored_date": "2017-07-19",

                "sponsor_title": "Rep.",
                "sponsor_id": "B000574",
                "sponsor_name": "Earl Blumenauer",
                "sponsor_state": "OR",
                "sponsor_party": "D",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/B000574.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/3305",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr3305",
                "introduced_date": "2017-07-19",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 2,
                "cosponsors_by_party": {
                    "R": 1,
                    "D": 1
                },
                "committees": "House Transportation and Infrastructure Committee",
                "primary_subject": "Transportation and Public Works",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-07-20",
                "latest_major_action": "Referred to the Subcommittee on Highways and Transit."
            },
            {
                "congress": "115",
                "bill_id": "hr2651-115",
                "bill_type": "hr",
                "number": "H.R.2651",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr2651.json",
                "title": "To improve the integrity and safety of horseracing by requiring a uniform anti-doping and medication control program to be developed and enforced by an independent Horseracing Anti-Doping and Medication Control Authority.",
                "short_title": "Horseracing Integrity Act of 2017",
                "cosponsored_date": "2017-07-18",

                "sponsor_title": "Rep.",
                "sponsor_id": "B001282",
                "sponsor_name": "Andy Barr",
                "sponsor_state": "KY",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/B001282.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/2651",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr2651",
                "introduced_date": "2017-05-25",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 102,
                "cosponsors_by_party": {
                    "D": 56,
                    "R": 43
                },
                "committees": "House Energy and Commerce Committee",
                "primary_subject": "Sports and Recreation",
                "summary": "",
                "summary_short": "",
                "latest_major_action_date": "2017-05-26",
                "latest_major_action": "Referred to the Subcommittee on Digital Commerce and Consumer Protection."
            },
            {
                "congress": "115",
                "bill_id": "hr1235-115",
                "bill_type": "hr",
                "number": "H.R.1235",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr1235.json",
                "title": "To require the Secretary of the Treasury to mint coins in recognition of the 60th Anniversary of the Naismith Memorial Basketball Hall of Fame.",
                "short_title": "Naismith Memorial Basketball Hall of Fame Commemorative Coin Act",
                "cosponsored_date": "2017-07-14",

                "sponsor_title": "Rep.",
                "sponsor_id": "N000015",
                "sponsor_name": "Richard E. Neal",
                "sponsor_state": "MA",
                "sponsor_party": "D",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/N000015.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/1235",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr1235",
                "introduced_date": "2017-02-27",
                "active": true,
                "last_vote": null,
                "house_passage": "2017-09-25",
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 291,
                "cosponsors_by_party": {
                    "R": 95,
                    "D": 196
                },
                "committees": "Senate Banking, Housing, and Urban Affairs Committee",
                "primary_subject": "Sports and Recreation",
                "summary": "Naismith Memorial Basketball Hall of Fame Commemorative Coin Act This bill directs the Department of the Treasury to mint and issue not more than 50,000 $5 coins, 400,000 $1 coins, and 750,000 half-dollar coins in recognition and celebration of the Naismith Memorial Basketball Hall of Fame. The coins shall be in the shape of a dome, and the design on the common reverse of the coins shall depict a basketball. Treasury shall hold a competition to determine the design of the common obverse of the coins, which shall be emblematic of the game of basketball. The bill requires all sales of such coins to include specified surcharges, which shall be paid by Treasury to the Hall to fund an endowment for increased operations and educational programming.",
                "summary_short": "Naismith Memorial Basketball Hall of Fame Commemorative Coin Act This bill directs the Department of the Treasury to mint and issue not more than 50,000 $5 coins, 400,000 $1 coins, and 750,000 half-dollar coins in recognition and celebration of the Naismith Memorial Basketball Hall of Fame. The coins shall be in the shape of a dome, and the design on the common reverse of the coins shall depict a basketball. Treasury shall hold a competition to determine the design of the common obverse of th...",
                "latest_major_action_date": "2017-09-26",
                "latest_major_action": "Received in the Senate and Read twice and referred to the Committee on Banking, Housing, and Urban Affairs."
            },
            {
                "congress": "115",
                "bill_id": "hr490-115",
                "bill_type": "hr",
                "number": "H.R.490",
                "bill_uri": "https://api.propublica.org/congress/v1/115/bills/hr490.json",
                "title": "To amend title 18, United States Code, to prohibit abortion in cases where a fetal heartbeat is detectable.",
                "short_title": "Heartbeat Protection Act of 2017",
                "cosponsored_date": "2017-06-29",

                "sponsor_title": "Rep.",
                "sponsor_id": "K000362",
                "sponsor_name": "Steve King",
                "sponsor_state": "IA",
                "sponsor_party": "R",
                "sponsor_uri": "https://api.propublica.org/congress/v1/members/K000362.json",
                "gpo_pdf_uri": null,
                "congressdotgov_url": "https://www.congress.gov/bill/115th-congress/house-bill/490",
                "govtrack_url": "https://www.govtrack.us/congress/bills/115/hr490",
                "introduced_date": "2017-01-12",
                "active": false,
                "last_vote": null,
                "house_passage": null,
                "senate_passage": null,
                "enacted": null,
                "vetoed": null,
                "cosponsors": 169,
                "cosponsors_by_party": {
                    "R": 168,
                    "D": 1
                },
                "committees": "House Judiciary Committee",
                "primary_subject": "Crime and Law Enforcement",
                "summary": "Heartbeat Protection Act of 2017 This bill amends the federal criminal code to make it a crime for a physician to knowingly perform an abortion: (1) without determining whether the fetus has a detectable heartbeat, (2) without informing the mother of the results, or (3) after determining that a fetus has a detectable heartbeat.  It provides an exception for an abortion that is necessary to save the life of a mother whose life is endangered by a physical (but not psychological or emotional) disorder, illness, or condition.  A physician who performs a prohibited abortion is subject to criminal penalties—a fine, up to five years in prison, or both.  A woman who undergoes a prohibited abortion may not be prosecuted for violating or conspiring to violate the provisions of this bill.",
                "summary_short": "Heartbeat Protection Act of 2017 This bill amends the federal criminal code to make it a crime for a physician to knowingly perform an abortion: (1) without determining whether the fetus has a detectable heartbeat, (2) without informing the mother of the results, or (3) after determining that a fetus has a detectable heartbeat.  It provides an exception for an abortion that is necessary to save the life of a mother whose life is endangered by a physical (but not psychological or emotional) di...",
                "latest_major_action_date": "2017-02-06",
                "latest_major_action": "Referred to the Subcommittee on Crime, Terrorism, Homeland Security, and Investigations."
            }
        ]
    }]
}
