{
   "status":"OK",
   "copyright":"Copyright (c) 2016 Pro Publica Inc. All Rights Reserved.",
   "results":[
      {
         "first_member_api_uri": "https://api.propublica.org/congress/v1/members/B001283.json",
         "second_member_api_uri": "https://api.propublica.org/congress/v1/members/C001101.json",
         "chamber": "House",
         "congress": "114",
         "common_bills": "15",
         "bills": [
          {
           "number": "H.R.1769",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr1769.json",
           "title": "Toxic Exposure Research Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/B001271.json",
           "introduced_date": "2015-04-14",
           "cosponsors": "188",
           "committees": "House Veterans&#39; Affairs Committee",
           "latest_major_action_date": "2016-02-25",
           "latest_major_action": "Ordered to be Reported in the Nature of a Substitute (Amended) by Voice Vote.",
           "first_member_date": "2015-09-08",
           "second_member_date": "2015-12-10"
          },
                  {
           "number": "H.R.969",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr969.json",
           "title": "Blue Water Navy Vietnam Veterans Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/G000564.json",
           "introduced_date": "2015-02-13",
           "cosponsors": "309",
           "committees": "House Veterans&#39; Affairs Committee",
           "latest_major_action_date": "2015-03-06",
           "latest_major_action": "Referred to the Subcommittee on Disability Assistance and Memorial Affairs.",
           "first_member_date": "2015-02-13",
           "second_member_date": "2015-02-13"
          },
                  {
           "number": "H.R.699",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr699.json",
           "title": "Email Privacy Act",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/Y000063.json",
           "introduced_date": "2015-02-04",
           "cosponsors": "314",
           "committees": "House Judiciary Committee",
           "latest_major_action_date": "2015-12-01",
           "latest_major_action": "Committee Hearings Held.",
           "first_member_date": "2015-07-27",
           "second_member_date": "2015-02-04"
          },
                  {
           "number": "H.R.842",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr842.json",
           "title": "Huntington&#39;s Disease Parity Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/K000378.json",
           "introduced_date": "2015-02-10",
           "cosponsors": "245",
           "committees": "House Ways and Means Committee",
           "latest_major_action_date": "2015-02-10",
           "latest_major_action": "Referred to the House Committee on Ways and Means.",
           "first_member_date": "2015-04-21",
           "second_member_date": "2015-02-10"
          },
                  {
           "number": "H.R.1220",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr1220.json",
           "title": "Removing Barriers to Colorectal Cancer Screening Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/D000604.json",
           "introduced_date": "2015-03-03",
           "cosponsors": "237",
           "committees": "House Energy and Commerce Committee",
           "latest_major_action_date": "2015-03-06",
           "latest_major_action": "Referred to the Subcommittee on Health.",
           "first_member_date": "2015-10-07",
           "second_member_date": "2015-07-28"
          },
                  {
           "number": "H.R.563",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr563.json",
           "title": "Honoring Our WWII Merchant Mariners Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/H001063.json",
           "introduced_date": "2015-01-27",
           "cosponsors": "66",
           "committees": "House Veterans&#39; Affairs Committee",
           "latest_major_action_date": "2015-02-06",
           "latest_major_action": "Referred to the Subcommittee on Disability Assistance and Memorial Affairs.",
           "first_member_date": "2015-07-09",
           "second_member_date": "2016-03-21"
          },
                  {
           "number": "H.R.160",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr160.json",
           "title": "Protect Medical Innovation Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/P000594.json",
           "introduced_date": "2015-01-06",
           "cosponsors": "282",
           "committees": "House Ways and Means Committee",
           "latest_major_action_date": "2015-06-23",
           "latest_major_action": "Read the second time. Placed on Senate Legislative Calendar under General Orders. Calendar No. 125.",
           "first_member_date": "2015-01-06",
           "second_member_date": "2015-01-06"
          },
                  {
           "number": "H.R.1384",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr1384.json",
           "title": "Honor America&#39;s Guard-Reserve Retirees Act",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/W000799.json",
           "introduced_date": "2015-03-16",
           "cosponsors": "132",
           "committees": "House Veterans&#39; Affairs Committee",
           "latest_major_action_date": "2015-11-17",
           "latest_major_action": "Received in the Senate and Read twice and referred to the Committee on Veterans&#39; Affairs.",
           "first_member_date": "2015-07-21",
           "second_member_date": "2015-06-08"
          },
                  {
           "number": "H.R.985",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr985.json",
           "title": "Concrete Masonry Products Research, Education, and Promotion Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/G000558.json",
           "introduced_date": "2015-02-13",
           "cosponsors": "244",
           "committees": "House Energy and Commerce Committee",
           "latest_major_action_date": "2015-07-29",
           "latest_major_action": "Ordered to be Reported (Amended) by Voice Vote.",
           "first_member_date": "2015-11-17",
           "second_member_date": "2015-03-17"
          },
                  {
           "number": "H.R.2567",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr2567.json",
           "title": "To posthumously award the Congressional Gold Medal to each of Glen Doherty, Tyrone Woods, J. Christopher Stevens, and Sean Smith in recognition of their contributions to the Nation.",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/Z000018.json",
           "introduced_date": "2015-05-21",
           "cosponsors": "59",
           "committees": "House Financial Services Committee",
           "latest_major_action_date": "2015-05-21",
           "latest_major_action": "Referred to the House Committee on Financial Services.",
           "first_member_date": "2015-05-21",
           "second_member_date": "2015-05-21"
          },
                  {
           "number": "H.R.1312",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr1312.json",
           "title": "National Health Service Corps Improvement Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/M001159.json",
           "introduced_date": "2015-03-04",
           "cosponsors": "114",
           "committees": "House Energy and Commerce Committee",
           "latest_major_action_date": "2015-03-06",
           "latest_major_action": "Referred to the Subcommittee on Health.",
           "first_member_date": "2015-03-19",
           "second_member_date": "2015-07-22"
          },
                  {
           "number": "H.R.1100",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr1100.json",
           "title": "Military Spouse Job Continuity Act of 2015",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/C001090.json",
           "introduced_date": "2015-02-26",
           "cosponsors": "143",
           "committees": "House Ways and Means Committee",
           "latest_major_action_date": "2015-02-26",
           "latest_major_action": "Referred to the House Committee on Ways and Means.",
           "first_member_date": "2015-07-23",
           "second_member_date": "2015-02-26"
          },
                  {
           "number": "H.R.1174",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hr1174.json",
           "title": "Law Enforcement Access to Data Stored Abroad Act",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/M001179.json",
           "introduced_date": "2015-02-27",
           "cosponsors": "136",
           "committees": "House Judiciary Committee",
           "latest_major_action_date": "2015-03-31",
           "latest_major_action": "Referred to the Subcommittee on Crime, Terrorism, Homeland Security, and Investigations.",
           "first_member_date": "2016-03-21",
           "second_member_date": "2015-06-08"
          },
                  {
           "number": "H.CON.RES.75",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hconres75.json",
           "title": "Expressing the sense of Congress that the atrocities perpetrated by ISIL against religious and ethnic minorities in Iraq and Syria include war crimes, crimes against humanity, and genocide.",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/F000449.json",
           "introduced_date": "2015-09-09",
           "cosponsors": "213",
           "committees": "House Foreign Relations Committee",
           "latest_major_action_date": "2016-03-15",
           "latest_major_action": "Received in the Senate and referred to the Committee on Foreign Relations.",
           "first_member_date": "2016-02-09",
           "second_member_date": "2015-10-09"
          },
                  {
           "number": "H.CON.RES.17",
           "api_uri": "https://api.propublica.org/congress/v1/114/bills/hconres17.json",
           "title": "Supporting the Local Radio Freedom Act.",
           "sponsor_uri": "https://api.propublica.org/congress/v1/members/C001062.json",
           "introduced_date": "2015-02-24",
           "cosponsors": "227",
           "committees": "House Judiciary Committee",
           "latest_major_action_date": "2015-03-17",
           "latest_major_action": "Referred to the Subcommittee on Courts, Intellectual Property, and the Internet.",
           "first_member_date": "2015-04-22",
           "second_member_date": "2016-02-25"
          }
        ]
      }
   ]
}
